name: ci

on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21.x"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Run test
        run: make test

  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build binaries
      run: make build

    - name: Create release archive
      run: tar -czf ./release.tar.gz ./gomutate

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        artifacts: release.tar.gz